apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: crossplane-state-metrics
  labels:
    app.kubernetes.io/name: crossplane-state-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: crossplane-state-metrics
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 60s
      scrapeTimeout: 50s
